### ISSUE TITLE
`go install` fails with "module ... found but does not contain package ..."

### ISSUE THREAD

**Issue by rehandaphedar** [etkecc/emm#1]
Hi, great project, especially useful as a psuedo CMS for Hugo!

On Arch Linux, with `go version go1.23.0 linux/amd64`, running `go install github.com/etkecc/emm@latest` fails with:
```
go: github.com/etkecc/emm@latest: module github.com/etkecc/emm@latest found (v0.9.8), but does not contain package github.com/etkecc/emm
```

I thought the golang proxy cache might have gotten stale, so I tried with `GOPROXY=direct`, still fails.

Manually building after cloning the repository works.
For now, I'm using the AUR package, which also works.

`go.mod` does contain `module github.com/etkecc/emm`. However, there is no `main.go` file in the root directory, which I suspect is the cause.

Running `go install github.com/etkecc/emm/cmd@latest` works, but it installs the binary as `cmd`, not as `emm`.

Also, I see that `cmd/main.go` contains `package main` instead of `package cmd`.

The solution seems to be to move/rename `cmd/main.go` to `main.go`, as per [the golang documentation](https://go.dev/doc/modules/layout).

**Comment by rehandaphedar** [comment]
Oh great speed! I was just about to make a PR for this.

**Comment by aine-etke** [comment]
Thank you for bringing this to our attention!
The fix is available in the [latest release](https://github.com/etkecc/emm/releases/tag/v0.9.9)
